services:
  rc_website_v2:
    container_name: rc_website_v2
    image: node:lts
    working_dir: /app
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - ./rc-website:/app
    #command: yarn dev
